version: '3.1'
services:
  postgres:
    image: postgres:12.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_orders
    ports:
      - 5432:5432
